# Copyright (C) 2024 Maizil41 https://github.com/maizil41
#
name: Build OpenWRT Rootfs

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Openwrt_ver:
        description: 'Select OpenWrt Version'
        required: true
        default: '24.10.x'
        type: choice
        options:
          - '22.03.0'
          - '22.03.1'
          - '22.03.2'
          - '22.03.3'
          - '22.03.4'
          - '22.03.5'
          - '22.03.6'
          - '22.03.7'
          - '23.05.0'
          - '23.05.1'
          - '23.05.2'
          - '23.05.3'
          - '23.05.4'
          - '23.05.5'
          - '24.10.0-rc1'
          - '24.10.0-rc2'
          - '24.10.0-rc3'
          - '24.10.0-rc4'
          - '24.10.0-rc5'
          - '24.10.0-rc6'
          - '24.10.0-rc7'
      openwrt_target:
        description: 'Select OpenWrt Targets'
        required: true
        default: 'armsr/armv8'
        type: choice
        options:
          - 'armsr/armv8'
      tunnel:
        description: 'Select Tunnel To Install'
        required: true
        default: 'All'
        type: choice
        options:
          - 'All'
          - 'Openclash'
          - 'Mihomo'
      rakitan:
        description: 'Modem Rakitan Support'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  make_rootfs:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update -y > /dev/null 2>&1
        sudo apt install net-tools make gawk git curl unzip bzip2 tar zstd -y > /dev/null 2>&1
        sudo apt install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt) > /dev/null 2>&1

    - name: Download Image Builder
      run: |
        wget -q "${{ github.event.inputs.builder_link }}" > /dev/null 2>&1

    - name: Extract Image Builder
      run: |
        filename=$(echo "${{ github.event.inputs.builder_link }}" | awk -F "/" '{print $NF}')
        # extension=$(echo "$filename" | awk -F'.' '{print $(NF-1)"."$NF}')
        # no_extension=$(basename "$filename" | sed "s/\.$extension$//")
        mkdir -p OpenWrt-Builder
        tar -x -f ${filename} -C OpenWrt-Builder --strip-components=1
        mv packages/* OpenWrt-Builder/packages/
        mv files OpenWrt-Builder
        chmod -R 755 OpenWrt-Builder/files/*
        
    - name: Build OpenWRT Rootfs
      run: |
        cd OpenWrt-Builder
        
        PACKAGES=" \
        -dnsmasq -luci-theme-bootstrap \
        dnsmasq-full cgi-io libiwinfo libiwinfo-data libiwinfo-lua liblua liblucihttp liblucihttp-lua \
        libubus-lua lua luci luci-app-firewall luci-app-opkg luci-base luci-lib-base \
        luci-lib-ip luci-lib-jsonc luci-lib-nixio luci-mod-admin-full luci-mod-network \
        luci-mod-status luci-mod-system luci-proto-ipv6 luci-proto-ppp luci-ssl \
        luci-theme-material rpcd rpcd-mod-file rpcd-mod-iwinfo rpcd-mod-luci \
        rpcd-mod-rrdns uhttpd uhttpd-mod-ubus luci-compat \
        ath9k-htc-firmware btrfs-progs hostapd hostapd-utils kmod-ath kmod-ath9k kmod-ath9k-common \
        kmod-ath9k-htc kmod-cfg80211 kmod-crypto-acompress kmod-crypto-crc32c kmod-crypto-hash \
        kmod-fs-btrfs kmod-mac80211 wireless-tools wpa-cli wpa-supplicant libc \
        php8 php8-cgi php8-mod-session php8-mod-ctype php8-mod-fileinfo php8-mod-zip php8-mod-iconv php8-mod-mbstring \
        zoneinfo-core zoneinfo-asia nano htop unzip wget wget-ssl libmbedtls tar bash  \
        netdata httping coreutils-timeout kmod-usb-net-rndis iperf3 \
        usbutils kmod-usb-net-cdc-ether usb-modeswitch openssh-sftp-server kmod-usb2 \
        kmod-usb-net-huawei-cdc-ncm kmod-usb-serial-wwan \
        perlbase-file kmod-brcmutil perlbase-essential perlbase-utf8 \
        perlbase-file  perlbase-time perlbase-xsloader coreutils-stat sudo \
        luci-app-ttyd luci-app-amlogic luci-app-diskman"

        if [[ "${{ github.event.inputs.tunnel }}" == "All" ]]; then
          PACKAGES="$PACKAGES luci-app-mihomo luci-app-openclash"
        elif [[ "${{ github.event.inputs.tunnel }}" == "Openclash" ]]; then
          PACKAGES="$PACKAGES luci-app-openclash"
        elif [[ "${{ github.event.inputs.tunnel }}" == "Mihomo" ]]; then
          PACKAGES="$PACKAGES luci-app-mihomo"
        fi

        if [[ "${{ github.event.inputs.rakitan }}" == "true" ]]; then
          PACKAGES="$PACKAGES kmod-mii kmod-usb-net kmod-usb-wdm kmod-usb-net-qmi-wwan uqmi luci-proto-qmi \
          kmod-usb-net-cdc-ether kmod-usb-serial-option kmod-usb-serial kmod-usb-serial-wwan qmi-utils \
          kmod-usb-serial-qualcomm kmod-usb-acm kmod-usb-net-cdc-ncm kmod-usb-net-cdc-mbim umbim \
          modemmanager luci-proto-modemmanager"
        fi

        make image PROFILE="generic" PACKAGES="$PACKAGES" FILES="files" || true

    - name: Find Rootfs
      run: |
        FILE_PATH=$(find -name "*rootfs.tar.gz" | head -n 1)
        echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV
        echo -e "Found Rootfs Path: $FILE_PATH"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
        name: Mutiara-Wrt ${{ github.event.inputs.openwrt_ver }}
        tag_name: ${{ github.event.inputs.openwrt_ver }}
        draft: false
        prerelease: false
        files: |
              ${{ env.FILE_PATH }}
        body: |
              Rootfs
